/**
 * Shared helpers for the database command-line tools (TASK-0101, ADR-015).
 *
 * The admin connection (`DATABASE_URL` + `SUPABASE_DB_PASSWORD`) bypasses row level security,
 * so only migrations, backups and the runtime-role command use it; the application server never
 * reads these variables. Every connection verifies the server certificate against the pinned
 * root CA. Nothing here prints a URL, password or full driver error.
 */
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import pg from "pg";

export const ROOT = resolve(import.meta.dirname, "..");
export const ENV_PATH = resolve(ROOT, ".env.local");
export const DEFAULT_CA_PATH = resolve(ROOT, "db/certs/supabase-root-2021-ca.crt");
export const APP_ROLE = "geoges_app";

/** Parses a dotenv file: `KEY=value`, optional surrounding quotes, `#` comment lines. */
export function parseEnv(text) {
  const env = {};
  for (const line of text.split(/\r?\n/)) {
    if (!line || line.trimStart().startsWith("#") || !line.includes("=")) continue;
    const i = line.indexOf("=");
    env[line.slice(0, i).trim()] = line
      .slice(i + 1)
      .trim()
      .replace(/^(["'])(.*)\1$/, "$2");
  }
  return env;
}

/**
 * `.env.local` when present, with process environment values filling the keys it lacks. CI has
 * no `.env.local`; it passes the throw-away database's settings as environment variables.
 */
export function readEnvFile(path = ENV_PATH) {
  const file = existsSync(path) ? parseEnv(readFileSync(path, "utf8")) : {};
  return { ...process.env, ...file };
}

/**
 * Splits a connection string by hand: passwords generated by Supabase may contain characters
 * that are not URL-encoded (`?`, `(`, `,`), which `new URL` would misread.
 */
export function parseConnectionString(raw) {
  const rest = raw.replace(/^postgres(ql)?:\/\//, "");
  const at = rest.lastIndexOf("@");
  if (at < 0) throw new Error("connection string has no user part");
  const auth = rest.slice(0, at);
  const colon = auth.indexOf(":");
  const user = colon < 0 ? auth : auth.slice(0, colon);
  const password = colon < 0 ? "" : auth.slice(colon + 1);
  const [hostPort, dbAndQuery = ""] = rest.slice(at + 1).split("/");
  const [host, port = "5432"] = hostPort.split(":");
  return {
    user,
    password,
    host,
    port: Number(port),
    database: dbAndQuery.split("?")[0] || "postgres",
  };
}

export function tlsOptions(host, caPath = DEFAULT_CA_PATH) {
  return { ca: readFileSync(caPath, "utf8"), rejectUnauthorized: true, servername: host };
}

/** Admin connection settings; the separate password line wins over the one inside the URL. */
export function adminConfig(env = readEnvFile()) {
  if (!env.DATABASE_URL) throw new Error("DATABASE_URL is missing from .env.local");
  const cfg = parseConnectionString(env.DATABASE_URL);
  if (env.SUPABASE_DB_PASSWORD) cfg.password = env.SUPABASE_DB_PASSWORD;
  return { ...cfg, ssl: tlsOptions(cfg.host, env.DATABASE_CA_CERT_PATH || DEFAULT_CA_PATH) };
}

export async function connectAdmin(env) {
  const client = new pg.Client({ ...adminConfig(env), connectionTimeoutMillis: 20_000 });
  await client.connect();
  return client;
}

/**
 * A driver error reduced to what is safe to print. Server errors (five-character SQLSTATE) keep
 * their message, which names objects, not credentials; connection errors keep only their code,
 * because their message can carry the host or the user name.
 */
export function safeError(error) {
  const code = error?.code ? String(error.code) : "no code";
  const serverError = /^[0-9A-Z]{5}$/.test(code) && error?.message;
  return serverError && !/password|postgres(ql)?:\/\//i.test(error.message)
    ? `${code}: ${error.message}`
    : code;
}
