export {
  capabilityCodes,
  defineAction,
  defineCapabilities,
  type ActionCapability,
  type CapabilityCaller,
  type CapabilityDataClass,
  type CapabilityStatus,
  type ConditionFieldCapability,
  type EventCapability,
  type ModuleCapabilities,
  type ListCapability,
  type OwnerRelationCapability,
  type RecordRef,
} from "@/platform/capabilities/catalog";
